package at.ac.tuwien.dsg.ElasticityInformationService.concepts;

public class LinkType {
	public static final String CLOUD_OFFER_SERVICE_BELONGS_TO_PROVIDER = "BELONGS_TO_PROVIDER";	
	public static final String CLOUD_OFFER_SERVICE_DERIVES_SERVICE_UNIT = "CLOUD_OFFER_SERVICE_DERIVES_SERVICE_UNIT";
	public static final String CLOUD_OFFER_SERVICE_HAS_RESOURCE = "CLOUD_OFFER_SERVICE_HAS_RESOURCE";
	public static final String CLOUD_OFFER_SERVICE_HAS_QUALITY = "CLOUD_OFFER_SERVICE_HAS_QUALITY";
	public static final String CLOUD_OFFER_SERVICE_HAS_COSTFUNCTION = "CLOUD_OFFER_SERVICE_HAS_COSTFUNCTION";
	
	public static final String SERVICE_UNIT_DEPLOYMENT_DEPENDENCY = "SERVICE_UNIT_DEPLOYMENT_DEPENDENCY";
	public static final String SERVICE_UNIT_ELASTICITY_DEPENDENCY = "SERVICE_UNIT_ELASTICITY_DEPENDENCY";	
}
