package at.ac.tuwien.dsg.comot.m.common;

public enum EpsAction {

	EPS_DYNAMIC_REQUESTED,
	EPS_DYNAMIC_CREATED,
	EPS_DYNAMIC_REMOVED,

	EPS_ASSIGNMENT_REQUESTED,
	EPS_ASSIGNED,
	EPS_ASSIGNMENT_REMOVED;
}
