package at.ac.tuwien.dsg.comot.m.common;

public enum EpsAction {

	EPS_DYNAMIC_REQUESTED,
	EPS_DYNAMIC_CREATED,
	EPS_DYNAMIC_REMOVED,

	EPS_SUPPORT_REQUESTED,
	EPS_SUPPORT_ASSIGNED,
	EPS_SUPPORT_REMOVED;
}
